[package]
name = "profiler-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "profiler"
path = "src/lib.rs"

[workspace]
members = [
	"profiler-attributes"
]

[dependencies]
profiler-attributes = { path = "profiler-attributes" }