[package]
name = "serialization_stress_test"
version = "0.1.0"
edition = "2021"

[dependencies]
profiler = { path = "../../", features = ["enable_profiling"] }
profiler_attributes = { path = "../../profiler_attributes" }