[package]
name = "optional_profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
profiler = { path = "../../" }
profiler_attributes = { path = "../../profiler_attributes" }


[features]
enable_profiling = ["profiler/enable_profiling"]